### PR TITLE
Check pointer to magnetic dataset before free

### LINKED ISSUE #348: get_magnetic_symmetry_dataset seg fault
When I try to get the magnetic dataset with large symprec, I get Segmentation fault (core dumped). It would be desirable to have similar behavior as the ordinary get_symmetry_dataset which returns None.

```
from spglib import get_magnetic_symmetry_dataset
from numpy import logspace
cell = ([[4, 0, 0.0],
         [0, 4, 0.0],
         [0, 0, 18]],
        [[0, 0, 0.57],
         [0.5, 0.5, 0.43],
         [0.5, 1, 0.5],
         [0, 0.5, 0.5]],
        [ 9,  9, 25, 25],
        [ 0,  0, -1,  1])

for symprec in logspace(-5, 1, 13):
    dataset = get_magnetic_symmetry_dataset(cell, symprec=symprec)
    print(dataset)
```

### PR DESCRIPTION
**Pull request by lan496**
Fixes https://github.com/spglib/spglib/issues/348

### CODE REVIEW

File: test/functional/c/test_magnetic_symmetry.cpp [hunk 1]
```diff
@@ -359,6 +359,27 @@ TEST(MagneticSymmetry, test_spg_get_symmetry_with_tensors_rough_symprec) {
...
+    int types[] = {1, 1, 2, 2};
+    double tensors[] = {0, 0, -1, 1};
+    int num_atoms = 4;
+    double symprec = 3.0;
+
+    SpglibMagneticDataset *dataset;
+    dataset = spg_get_magnetic_dataset(lattice, positions, types, tensors, 0,
+                                       num_atoms, 0, symprec);
+    // MSG identification is failed with the too high mag_symprec
+    ASSERT_TRUE(dataset == NULL);
```
Comment (LecrisUT) [inline test/functional/c/test_magnetic_symmetry.cpp]: Can do a few changes?
- `EXPECT_EQ` and `NULL` -> `nullptr`
- Add a check of `spgerror`

**Review by LecrisUT — CHANGES_REQUESTED** [review]

File: test/functional/c/test_magnetic_symmetry.cpp [hunk 2]
```diff
@@ -372,12 +372,16 @@ TEST(MagneticSymmetry, test_spg_get_magnetic_dataset_high_mag_symprec) {
...
 
     SpglibMagneticDataset *dataset;
     dataset = spg_get_magnetic_dataset(lattice, positions, types, tensors, 0,
                                        num_atoms, 0, symprec);
     // MSG identification is failed with the too high mag_symprec
-    ASSERT_TRUE(dataset == NULL);
+    EXPECT_EQ(dataset, nullptr);
+
+    error = spg_get_error_code();
+    EXPECT_NE(error, SpglibError::SPGLIB_SUCCESS);
```
Comment (LecrisUT) [inline test/functional/c/test_magnetic_symmetry.cpp]:
```suggestion
    auto error = spg_get_error_code();
    EXPECT_EQ(error, SpglibError::SPGERR_SPACEGROUP_SEARCH_FAILED);
```
Not sure what the error code should be, but we should test the cause more narrowly, rather than `EXPECT_NE(SPGLIB_SUCCESS)`

**Review by LecrisUT — CHANGES_REQUESTED** [review]

File: test/functional/c/test_magnetic_symmetry.cpp (hunk 2 above)
Comment (lan496) [reply test/functional/c/test_magnetic_symmetry.cpp]: Indeed. I've specified the error code `SpglibError::SPGERR_ATOMS_TOO_CLOSE` in this case. But, I'm not this error code is appropriate for this test case.

Comment (LecrisUT) [reply test/functional/c/test_magnetic_symmetry.cpp]: It's ok, that's the purpose of the CI to catch and make sure these are predictable.

Also about using `auto`, it would make the code a bit cleaner.

**Review by LecrisUT — APPROVED** [review]
