### PR TITLE
fix(fortran): Rrmove unused unsigned C types

### LINKED ISSUE #585: compilation error due to `C_unsigned` (flang 20)
Now gfortran 15 (with `-funsigned`) and flang 20 support `C_UNSIGNED` etc in `ISO_C_BINDING`:

- <https://gcc.gnu.org/onlinedocs/gcc-15.1.0/gfortran/ISO_005fC_005fBINDING.html>
- <https://gcc.gnu.org/onlinedocs/gcc-15.1.0/gfortran/Unsigned-integers.html>
- <https://flang.llvm.org/docs/Unsigned.html#standard-modules>

Therefore the following workaround will be no longer necessary:

https://github.com/spglib/spglib/blob/cff3a27f2556b19190721bde20427aa5a60cabb2/test/functional/fortran/c_interface_module.F90#L49-L69

Actually, spglib does not compile with flang:

```
error: Semantic errors in test/CMakeFiles/Spglib_Fortran_tests.dir/functional/fortran/c_interface_module.F90-pp.f90
test/functional/fortran/c_interface_module.F90:50:29: error: PARAMETER attribute was already specified on 'c_unsigned'
        integer, parameter :: C_unsigned = C_int, C_unsigned_short = C_sho&
                              ^^^^^^^^^^
test/functional/fortran/c_interface_module.F90:50:29: error: 'c_unsigned' is use-associated from module 'iso_c_binding' and cannot be re-declared
        integer, parameter :: C_unsigned = C_int, C_unsigned_short = C_sho&
                              ^^^^^^^^^^
…
```

`-fno-unsigned` seems to have no effect.

### PR DESCRIPTION
**Pull request by e-kwsm**
fix #585

### CODE REVIEW

File: test/functional/fortran/c_interface_module.F90 [hunk 1]
```diff
@@ -46,6 +46,7 @@ module C_interface_module
     ! include support for more character types.
     !
 
+#ifndef Spglib_HAS_C_UNSIGNED
     ! Fortran does not (yet) support unsigned types.
     integer, parameter :: &
         C_unsigned = C_int, &
```
Comment (LecrisUT) [inline test/functional/fortran/c_interface_module.F90]: Wait, this is only used in the test interface? Can you investigate if these can be dropped instead?

Comment (e-kwsm) [reply test/functional/fortran/c_interface_module.F90]: Yeah, the variables are actually unnecessary.

**Comment by LecrisUT** [comment]
Awesome, thanks for this. I'll try to fix the test failure soon and then the automation will take over to merge this
