### PR TITLE
Niggli reduction before finding hall number from symmetry operations

### LINKED ISSUE #584: spg_get_spacegroup_type_from_symmetry fails to find Fdd2 from non-standard primitive setting
Using  `spg_get_spacegroup_type_from_symmetry` fails to find the correct spacegroup for orthorhombic F ( Fdd2) when the primitive lattice vectors are expressed in a non-standard basis.  To get this non-standard basis, the lattice vectors have been transformed by the matrix
`(1,0,0)(-1,1,0)(-1,-1,1)`.

The attached example code demonstrates this, returning "C2" for the alternate setting while giving the correct "Fdd2" for the conventional primitive basis.  I tried to figure out what is failing, but I'm afraid the complexities of spglib's search strategy defeated my attempts.  I might guess that it has something to do with  the rotations containing entries of "2" even though the transformation is volume-preserving.  

On the other hand `spg_get_dataset` succeeds in both the conventional primitive and alternate basis. The test set is based on structure 1509692 in the crystallography open database.

[test-spg-get-type.c.gz](https://github.com/user-attachments/files/20576485/test-spg-get-type.c.gz)

[Ag2O3-1509692-alt.cif.gz](https://github.com/user-attachments/files/20576602/Ag2O3-1509692-alt.cif.gz)

[Ag2O3-1509692.cif.gz](https://github.com/user-attachments/files/20576603/Ag2O3-1509692.cif.gz)

### PR DESCRIPTION
**Pull request by atztogo**
Fix #584

### CODE REVIEW

**Comment by atztogo** [comment]
Wrote a test in C. I suppose this is covered by CI. Am I correct, @LecrisUT?

File: test/functional/c/test_spacegroup_type_search.cpp [hunk 1]
```diff
@@ -39,3 +39,34 @@ TEST(SpacegroupTypeSearch, test_spg_get_schoenflies) {
...
+                            {0.3584, 0.2650, 0.4292}, {0.1716, 0.7650, 0.5858},
+                            {0.6994, 0.5334, 0.2150}, {0.3674, 0.0334, 0.2990},
+                            {0.3006, 0.4666, 0.5156}, {0.0000, 0.0000, 0.5902},
+                            {0.0000, 0.5000, 0.8402}, {0.6326, 0.9666, 0.9316}};
+    int types[] = {1, 1, 1, 1, 6, 6, 6, 6, 6, 6};
+    int num_atom = 10;
+
+    dataset = spg_get_dataset(lattice, position, types, num_atom, 1e-5);
+
+    ASSERT_EQ(dataset->hall_number, 212);
```
Comment (LecrisUT) [inline test/functional/c/test_spacegroup_type_search.cpp]: Can you add an `ASSERT_EQ` that dataset is not null and change the other ones to be `CHECK_EQ` so that we don't miss the destructor.

**Review by LecrisUT — COMMENTED** [review]
You can also put the tests in the python side. Eventually we will have to consolidate them, but until then I don't mind where they are.

File: test/functional/c/test_spacegroup_type_search.cpp (hunk 1 above)
Comment (atztogo) [reply test/functional/c/test_spacegroup_type_search.cpp]: [cde2282](https://github.com/spglib/spglib/pull/589/commits/cde2282a9e9711f5aca0192705b9b18af45aa02b)

**Comment by atztogo** [comment]
I found a critical bug in python interface.

https://github.com/spglib/spglib/blob/36a39380cfcba011be9d68a1a93ba80c5b978d74/python/spglib/spglib.py#L1158

This `lattice` has to be transposed. I think this as well, @lan496?

https://github.com/spglib/spglib/blob/36a39380cfcba011be9d68a1a93ba80c5b978d74/python/spglib/spglib.py#L1252

Should I be better to make another PR for this fix?

**Comment by LecrisUT** [comment]
> I found a critical bug in python interface.

I did find some inconsistencies, where the transpose is done on the Cpp side. Don't remember which ones these are, but I will try to consolidate them in #579 and do them all in the cpp side.

Edit: Checked the cpp side. It's not transposed there either :/

File: test/functional/c/test_spacegroup_type_search.cpp [hunk 2]
```diff
@@ -39,3 +39,34 @@ TEST(SpacegroupTypeSearch, test_spg_get_schoenflies) {
...
+    double position[][3] = {{0.6416, 0.7350, 0.0708}, {0.8284, 0.2350, 0.4142},
+                            {0.3584, 0.2650, 0.4292}, {0.1716, 0.7650, 0.5858},
+                            {0.6994, 0.5334, 0.2150}, {0.3674, 0.0334, 0.2990},
+                            {0.3006, 0.4666, 0.5156}, {0.0000, 0.0000, 0.5902},
+                            {0.0000, 0.5000, 0.8402}, {0.6326, 0.9666, 0.9316}};
+    int types[] = {1, 1, 1, 1, 6, 6, 6, 6, 6, 6};
+    int num_atom = 10;
+
+    dataset = spg_get_dataset(lattice, position, types, num_atom, 1e-5);
+    EXPECT_NE(dataset, nullptr);
```
Comment (LecrisUT) [inline test/functional/c/test_spacegroup_type_search.cpp]:
```suggestion
    ASSERT_NE(dataset, nullptr);
```
Minor change to avoid segfault in the next steps. Otherwise lgtm.

**Review by LecrisUT — APPROVED** [review]

**Comment by atztogo** [comment]
> Don't remember which ones these are,

https://github.com/spglib/spglib/blob/36a39380cfcba011be9d68a1a93ba80c5b978d74/python/spglib/spglib.py#L2054

In python, crystal structure is given in this [format](https://spglib.readthedocs.io/en/stable/python-interface.html#crystal-structure-cell), but for `get_spacegroup_type_from_symmetry`, only lattice (basis vectors) is given, so this transpose has to be handled in that function without relying on `_expand_cell` function.

**Comment by atztogo** [comment]
How about making another PR for the fix of the python interface? If this way, we can first merge this PR after approval, then I will make the fix and its PR.

**Comment by LecrisUT** [comment]
> How about making another PR for the fix of the python interface? If this way, we can first merge this PR after approval, then I will make the fix and its PR.

Of course. Do you think you can find a test where it breaks? Usually I make the test commit first and run the CI to confirm it actually breaks/covers the thing we are fixing (in this case I confirmed locally by reverting the commit).

**Comment by atztogo** [comment]
> Do you think you can find a test where it breaks? Usually I make the test commit first and run the CI to confirm it actually breaks/covers the thing we are fixing (in this case I confirmed locally by reverting the commit).

I will try in this way.

**Comment by lan496** [comment]
> I found a critical bug in python interface.

@atztogo I think it is better to separate PR

**Review by lan496 — APPROVED** [review]
LGTM

**Comment by lan496** [comment]
> Do you think you can find a test where it breaks?

Possibly, `get_spacegroup_type_from_symmetry` with a hexagonal lattice will return an unexpected result
