### PR TITLE
Throw python exceptions

### LINKED ISSUE #582: Incompatible function arguments in `develop` version
Dear developers,
Thank you for your work on this incredibly useful package.

I noticed that when installing the latest github version of `spglib` (with `pip install git+https://github.com/spglib/spglib --config-settings=cmake.define.SPGLIB_SHARED_LIBS=OFF`), I get this error with `get_symmetry_dataset()`. You may be aware of this, but just flagging if helpful!

```
cell = (((13.086768, 0.0, 0.0), (0.0, 13.086768, 0.0), (0.0, 0.0, 13.086768)), ((0.0, 0.0, 0.0), (0.0, 0.0, 0.5), (0.0, 0.5, 0.0), (0.0, 0.5, 0.5), (0.5, 0.0, 0.0), (0.5, 0.0, 0.5), ...), (1, 1, 1, 1, 1, 1, ...))
symprec = 0.1, angle_tolerance = 5, hall_number = 0

    def get_symmetry_dataset(
        cell: Cell,
        symprec: float = 1e-5,
        angle_tolerance: float = -1.0,
        hall_number: int = 0,
    ) -> SpglibDataset | None:
        """Search symmetry dataset from an input cell.
    
        Parameters
        ----------
        cell, symprec, angle_tolerance:
            See :func:`get_symmetry`.
        hall_number : int
            If a serial number of Hall symbol (>0) is given, the database
            corresponding to the Hall symbol is made.
    
            The mapping from Hall symbols to a space-group-type is the many-to-one mapping.
            Without specifying this
            option (i.e., in the case of ``hall_number=0``), always the first one
            (the smallest serial number corresponding to the space-group-type in
            [list of space groups (Seto's web site)](https://yseto.net/en/sg/sg1))
            among possible choices and settings is chosen as default. This
            argument is useful when the other choice (or setting) is expected to
            be hooked.
    
            This affects to the obtained values of `international`,
            `hall`, `choice`, `transformation_matrix`,
            `origin shift`, `wyckoffs`, `std_lattice`, `std_positions`,
            `std_types` and `std_rotation_matrix`, but not to `rotations`
            and `translations` since the later set is defined with respect to
            the basis vectors of user's input (the `cell` argument).
    
            See also :ref:`dataset_spg_get_dataset_spacegroup_type`.
    
        Returns
        -------
        dataset: :class:`SpglibDataset` | None
            If it fails, None is returned. Otherwise a dictionary is returned.
            More details are found at :ref:`spglib-dataset`.
    
        """
        _set_no_error()
    
        lattice, positions, numbers, _ = _expand_cell(cell)
    
>       spg_ds = _spglib.dataset(
            lattice,
            positions,
            numbers,
            hall_number,
            symprec,
            angle_tolerance,
        )
E       TypeError: dataset(): incompatible function arguments. The following argument types are supported:
E           1. (arg0: numpy.ndarray[numpy.float64], arg1: numpy.ndarray[numpy.float64], arg2: numpy.ndarray[numpy.int32], arg3: int, arg4: float, arg5: float) -> Optional[list]
E       
E       Invoked with: array([[13.086768,  0.      ,  0.      ],
E              [ 0.      , 13.086768,  0.      ],
E              [ 0.      ,  0.      , 13.086768]]), array([[0.   , 0.   , 0.   ],
E              [0.   , 0.   , 0.5  ],
E              [0.   , 0.5  , 0.   ],
E              [0.   , 0.5  , 0.5  ],
E              [0.5  , 0.   , 0.   ],
E              [0.5  , 0.   , 0.5  ],
E              [0.5  , 0.5  , 0.   ],
E              [0.5  , 0.5  , 0.5  ],
E              [0.   , 0.25 , 0.25 ],
E              [0.   , 0.25 , 0.75 ],
E              [0.   , 0.75 , 0.25 ],
E              [0.   , 0.75 , 0.75 ],
E              [0.5  , 0.25 , 0.25 ],
E              [0.5  , 0.25 , 0.75 ],
E              [0.5  , 0.75 , 0.25 ],
E              [0.5  , 0.75 , 0.75 ],
E              [0.25 , 0.   , 0.25 ],
E              [0.25 , 0.   , 0.75 ],
E              [0.25 , 0.5  , 0.25 ],
E              [0.25 , 0.5  , 0.75 ],
E              [0.75 , 0.   , 0.25 ],
E              [0.75 , 0.   , 0.75 ],
E              [0.75 , 0.5  , 0.25 ],
E              [0.75 , 0.5  , 0.75 ],
E              [0.25 , 0.25 , 0.   ],
E              [0.25 , 0.25 , 0.5  ],
E              [0.25 , 0.75 , 0.   ],
E              [0.25 , 0.75 , 0.5  ],
E              [0.75 , 0.25 , 0.   ],
E              [0.75 , 0.25 , 0.5  ],
E              [0.75 , 0.75 , 0.   ],
E              [0.75 , 0.75 , 0.5  ],
E              [0.125, 0.125, 0.375],
E              [0.125, 0.125, 0.875],
E              [0.125, 0.625, 0.375],
E              [0.125, 0.625, 0.875],
E              [0.625, 0.125, 0.375],
E              [0.625, 0.125, 0.875],
E              [0.625, 0.625, 0.375],
E              [0.625, 0.625, 0.875],
E              [0.125, 0.375, 0.125],
E              [0.125, 0.375, 0.625],
E              [0.125, 0.875, 0.125],
E              [0.125, 0.875, 0.625],
E              [0.625, 0.375, 0.125],
E              [0.625, 0.375, 0.625],
E              [0.625, 0.875, 0.125],
E              [0.625, 0.875, 0.625],
E              [0.375, 0.125, 0.125],
E              [0.375, 0.125, 0.625],
E              [0.375, 0.625, 0.125],
E              [0.375, 0.625, 0.625],
E              [0.875, 0.125, 0.125],
E              [0.875, 0.125, 0.625],
E              [0.875, 0.625, 0.125],
E              [0.875, 0.625, 0.625],
E              [0.375, 0.375, 0.375],
E              [0.375, 0.375, 0.875],
E              [0.375, 0.875, 0.375],
E              [0.375, 0.875, 0.875],
E              [0.875, 0.375, 0.375],
E              [0.875, 0.375, 0.875],
E              [0.875, 0.875, 0.375],
E              [0.875, 0.875, 0.875]]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
E              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
E              2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
E             dtype=int32), 0, 0.1, 5
```

### PR DESCRIPTION
**Pull request by LecrisUT**
TODO:
- [x] Make the library throw exceptions
- [x] Add a compatibility for the old error handling
- [x] Add more checks in the C++ code

Depends-on: #578 
Closes #582

### CODE REVIEW

**Comment by LecrisUT** [comment]
There were still some areas that I didn't manage to add proper checks on the cpp side, but it should be a good enough approach for now.

File: python/py_bindings.h [hunk 1]
```diff
@@ -18,99 +18,180 @@ using array_uintp =
     py::array_t<uintptr_t, py::array::c_style | py::array::forcecast>;
 using array_size_t =
     py::array_t<size_t, py::array::c_style | py::array::forcecast>;
+
+class Lattice {
```
Comment (lan496) [inline python/py_bindings.h:25]: Can you leave a note explaining why these classes were introduced in this PR? It is difficult to guess that this PR includes these changes only from the title and threads

File: ChangeLog.md [hunk 2]
```diff
@@ -25,6 +25,8 @@ GitHub release pages and in the git history.
 ### Python API
 
 - Switched to using pybind11 for generating the python bindings
+- Deprecated `get_error_message()` and `error` attributes.
+- Python functions can now raise exceptions. To opt-in set `spglib.OLD_ERROR_HANLDING=False`
```
Comment (lan496) [inline ChangeLog.md]: This PR will largely change how users call spglib. Can you write a snippet about how to catch the exception from spglib? Which exception is raised on the Python side, ValueError or something?

Comment (LecrisUT) [reply ChangeLog.md]: Hmm, indeed, let me see if I can quickly provide a common error type to raise.

Comment (LecrisUT) [reply ChangeLog.md]: Everything should throw a `SpglibError` unless it is something that we cannot control. Added some documentation as well.

File: python/py_bindings.h (hunk 1 above)
Comment (LecrisUT) [reply python/py_bindings.h:25]: Hmm, I added only a common comment at the top of these.

**Comment by lan496** [comment]
Some existing tests start to raise SpglibError and result in CI failure

**Comment by lan496** [comment]
@atztogo, can you also take a look at this PR?

**Comment by LecrisUT** [comment]
> Some existing tests start to raise SpglibError and result in CI failure

Ah, it's trivial. We have changed what the exception was being raised in that test and I forgot to adapt it

**Review by atztogo — APPROVED** [review]
LGTM. Thanks @LecrisUT!

**Review by lan496 — APPROVED** [review]
LGTM

**Comment by siteshwar** [comment]
There were some [deprecation warnings](https://openscanhub.fedoraproject.org/task/82755/log/added.html) reported by OpenScanHub that might be good to fix:

```
Error: COMPILER_WARNING ([CWE-477](https://cwe.mitre.org/data/definitions/477.html)): [[#def1]](https://openscanhub.fedoraproject.org/task/82755/log/added.html#def1)
spglib-2.6.0/python/py_bindings.cpp: scope_hint: In function ‘pybind11::dict spglib::layer_dataset(const Lattice&, const Positions&, const AtomTypes&, pybind11::int_, pybind11::float_)’
spglib-2.6.0/python/py_bindings.cpp:366:41: warning[-Wdeprecated-declarations]: ‘SpglibDataset* spg_get_layer_dataset(const double (*)[3], const double (*)[3], const int*, int, int, double)’ is deprecated: Experimental interface. May be removed in next major release.
#  366 |     auto dataset = spg_get_layer_dataset(lattice.data(), positions.data(),
#      |                    ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  367 |                                          atom_types.data(), atom_types.n_atoms,
#      |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  368 |                                          aperiodic_dir, symprec);
#      |                                          ~~~~~~~~~~~~~~~~~~~~~~~
spglib-2.6.0/python/py_bindings.cpp:4: included_from: Included from here.
spglib-2.6.0/include/spglib.h:212:24: note: declared here
#  212 | SPG_API SpglibDataset *spg_get_layer_dataset(
#      |                        ^~~~~~~~~~~~~~~~~~~~~
#  364|                                  AtomTypes const &atom_types,
#  365|                                  py::int_ aperiodic_dir, py::float_ symprec) {
#  366|->     auto dataset = spg_get_layer_dataset(lattice.data(), positions.data(),
#  367|                                            atom_types.data(), atom_types.n_atoms,
#  368|                                            aperiodic_dir, symprec);

Error: COMPILER_WARNING ([CWE-477](https://cwe.mitre.org/data/definitions/477.html)): [[#def2]](https://openscanhub.fedoraproject.org/task/82755/log/added.html#def2)
spglib-2.6.0/python/py_bindings.cpp: scope_hint: In function ‘pybind11::int_ spglib::symmetry(Rotations&, Translations&, const Lattice&, const Positions&, const AtomTypes&, pybind11::float_, pybind11::float_)’
spglib-2.6.0/python/py_bindings.cpp:492:34: warning[-Wdeprecated-declarations]: ‘int spgat_get_symmetry(int (*)[3][3], double (*)[3], int, const double (*)[3], const double (*)[3], const int*, int, double, double)’ is deprecated: Use the variables from SpglibDataset (rotations, translations)
#  492 |     auto val = spgat_get_symmetry(rotations.data(), translations.data(),
#      |                ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  493 |                                   rotations.n_operations, lattice.data(),
#      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  494 |                                   positions.data(), atom_types.data(),
#      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  495 |                                   atom_types.n_atoms, symprec, angle_tolerance);
#      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spglib-2.6.0/include/spglib.h:254:13: note: declared here
#  254 | SPG_API int spgat_get_symmetry(int rotation[][3][3], double translation[][3],
#      |             ^~~~~~~~~~~~~~~~~~
#  490|                             AtomTypes const &atom_types, py::float_ symprec,
#  491|                             py::float_ angle_tolerance) {
#  492|->     auto val = spgat_get_symmetry(rotations.data(), translations.data(),
#  493|                                     rotations.n_operations, lattice.data(),
#  494|                                     positions.data(), atom_types.data(),

Error: COMPILER_WARNING ([CWE-477](https://cwe.mitre.org/data/definitions/477.html)): [[#def3]](https://openscanhub.fedoraproject.org/task/82755/log/added.html#def3)
spglib-2.6.0/python/py_bindings.cpp: scope_hint: In function ‘pybind11::int_ spglib::hall_number_from_symmetry(const Rotations&, const Translations&, pybind11::float_)’
spglib-2.6.0/python/py_bindings.cpp:658:49: warning[-Wdeprecated-declarations]: ‘int spg_get_hall_number_from_symmetry(const int (*)[3][3], const double (*)[3], int, double)’ is deprecated: Use the variable from SpglibSpacegroupType instead (hall_number)
#  658 |     auto val = spg_get_hall_number_from_symmetry(
#      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
#  659 |         rotations.data(), translations.data(), rotations.n_operations, symprec);
#      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spglib-2.6.0/include/spglib.h:327:13: note: declared here
#  327 | SPG_API int spg_get_hall_number_from_symmetry(int const rotation[][3][3],
#      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  656|                                              Translations const &translations,
#  657|                                              py::float_ symprec) {
#  658|->     auto val = spg_get_hall_number_from_symmetry(
#  659|           rotations.data(), translations.data(), rotations.n_operations, symprec);
#  660|       if (val == 0) throw Spglib_classic_exception();
```

**Comment by LecrisUT** [comment]
Those are first-party deprecations (stuff we deprecated but we still offer the python interface).
