### PR TITLE
Take absolute value for calculating nubmer of lattice points

### LINKED ISSUE #515: Segmentation fault in `get_magnetic_symmetry_dataset`
The following MSG search results in segmentation fault.

```python
import numpy as np
from spglib import get_magnetic_symmetry_dataset, get_symmetry_dataset

cell = (
    np.array([
        [-2.85823589e-08,  6.41219485e+00,  4.53409959e+00],
        [ 5.55312336e+00, -3.20609746e+00,  4.53409960e+00],
        [-2.77656167e+00, -1.60304871e+00,  2.26704980e+00]
    ]),
    np.array([
        [1.36114730e-08, 1.25613580e-07, 9.99999841e-01],
        [2.49999880e-01, 2.50000091e-01, 1.71296187e-07],
        [2.50000020e-01, 8.12272043e-08, 4.99999899e-01],
        [7.45180680e-08, 2.50000089e-01, 4.99999615e-01],
        [9.99999885e-01, 4.99999961e-01, 7.51512471e-08],
        [2.49999937e-01, 7.49999899e-01, 3.42200749e-07],
        [2.49999990e-01, 4.99999997e-01, 4.99999929e-01],
        [9.99999967e-01, 7.49999890e-01, 5.00000321e-01],
        [4.99999988e-01, 9.99999973e-01, 1.07227458e-07],
        [7.49999930e-01, 2.50000088e-01, 9.99999941e-01],
        [7.49999928e-01, 9.99999913e-01, 5.00000252e-01],
        [5.00000016e-01, 2.49999991e-01, 4.99999988e-01],
        [5.00000131e-01, 4.99999971e-01, 9.99999904e-01],
        [7.50000138e-01, 7.49999926e-01, 9.99999880e-01],
        [7.50000037e-01, 5.00000064e-01, 4.99999880e-01],
        [5.00000061e-01, 7.49999939e-01, 4.99999858e-01]
    ]),
    np.array([1, 4, 4, 4, 1, 4, 4, 4, 1, 4, 4, 4, 1, 4, 4, 4]),
    np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
)

dataset = get_magnetic_symmetry_dataset(cell)
print(dataset)
```

### PR DESCRIPTION
**Pull request by lan496**
Closes https://github.com/spglib/spglib/issues/515

We need to take absolute value for a determinant of a transformation matrix to calculate cell size.

### CODE REVIEW

File: test/functional/c/test_magnetic_dataset.cpp [hunk 1]
```diff
@@ -362,4 +362,43 @@ TEST(MagneticDataset, test_failure_with_slightly_distorted_positions) {
     if (dataset) spg_free_magnetic_dataset(dataset);
 }
 
+TEST(MagneticDataset, test_with_right_handed_magnetic_lattice) {
+    double lattice[3][3] = {
```
Comment (LecrisUT) [inline test/functional/c/test_magnetic_dataset.cpp:369]: Can you add a comment here about the issue and that it covers an issue where the absolute value of determinant was taken?

**Review by LecrisUT — CHANGES_REQUESTED** [review]
Can you do a quick review of the other usages of determinant to see if something similar was missed somewhere else?

File: test/functional/c/test_magnetic_dataset.cpp (hunk 1 above)
Comment (lan496) [reply test/functional/c/test_magnetic_dataset.cpp:369]: Done

**Comment by lan496** [comment]
I've checked the other parts properly take absolute values of determinants.

**Comment by LecrisUT** [comment]
Here are a few ones that should be investigated:
https://github.com/spglib/spglib/blob/e13a16facac0687463948d8af70ed475a9942f60/src/spacegroup.c#L1316
https://github.com/spglib/spglib/blob/e13a16facac0687463948d8af70ed475a9942f60/src/spacegroup.c#L1366
https://github.com/spglib/spglib/blob/e13a16facac0687463948d8af70ed475a9942f60/src/spacegroup.c#L1517
https://github.com/spglib/spglib/blob/e13a16facac0687463948d8af70ed475a9942f60/src/spacegroup.c#L1661

**Comment by lan496** [comment]
I am not confident with the `mat_get_determinant_d3` in spacegroup.c.
@atztogo Are these if-statements fine without taking absolute values?

**Comment by atztogo** [comment]
`mat_get_determinant_d3(orig_lattice)  > symprec` in spacegroup.c is used to find (a, b, c) vectors similar to the user input basis vectors.

Depending on symmetry, spglib might result in permutations like (b, c, a), etc., but it tries to align to (a, b, c). If the input basis vectors are in a left-handed coordinate system, spglib does not attempt to align them.

**Comment by lan496** [comment]
> mat_get_determinant_d3(orig_lattice)  > symprec in spacegroup.c is used to find (a, b, c) vectors similar to the user input basis vectors.

I see. I understand abs are **not** required for these parts.

**Comment by LecrisUT** [comment]
I am still lost on this, probably because the naming `orig_lattice` is not descriptive. What happens if there are 2 permutations of the vector such that it is positive again? What does the determinant and its absolute mean in this case?

**Comment by atztogo** [comment]
> I am still lost on this, probably because the naming `orig_lattice` is not descriptive. What happens if there are 2 permutations of the vector such that it is positive again? What does the determinant and its absolute mean in this case?

I may not understand your question fully, but it happens. The determinant is mostly used for calculating the volume of the unit cell (primitive cell, conventional unit cell, some cell that arises intermediately, etc), for which we take absolute. The volume can be used for various check for consistency check. For example, volume is not around zero, ratio of volumes of two cells is about integer, etc. When we want to check right handed or left handed, we don't take absolute. Positive or negative is checked. If negative, in some routine, the basis vectors are changed to right handed.

**Comment by LecrisUT** [comment]
> I may not understand your question fully, but it happens. The determinant is mostly used for calculating the volume of the unit cell (primitive cell, conventional unit cell, some cell that arises intermediately, etc), for which we take absolute. The volume can be used for various check for consistency check. For example, volume is not around zero, ratio of volumes of two cells is about integer, etc. When we want to check right handed or left handed, we don't take absolute. Positive or negative is checked. If negative, in some routine, the basis vectors are changed to right handed.

Ok, but what about in the context of the 4 snippets above? According to the explanation it is only checking if the basis set is right-handed, but then why does it completely throw away the left-handed ones? Is it always supposed to be right-handed in that case, and if so an `assert` should be added to clarify it. Why are some checks against `mat_get_determinant_d3()  < 0`, while the inverse is against `mat_get_determinant_d3()  > symprec` if they are only checking for left/right handiness.

**Comment by atztogo** [comment]
It is not theoretical. It is just for letting users feel better. This is not a mandatory procedure. So we don't need to be strict.

Spglib returns transformation matrix, which suggest basis vectors of a conventinal unit cell (a_s, b_s, c_s) as written athttps://spglib.readthedocs.io/en/latest/definition.html#transformation-matrix-boldsymbol-p-and-origin-shift-boldsymbol-p.

If the user input cell (a, b, c) is right handed and conventional unit cell, I wanted to return similar basis vectors in Cartesian coordinates, (a, b, c) ~ (a_s, b_s, c_s). But since the returned basis vectors must be right handed per definition, if the user input cell is left handed, these never become similar. So searching similar basis vectors is not performed.

**Review by LecrisUT — APPROVED** [review]
Ok, I guess that clarifies that point
