### PR TITLE
Validate type of MSG

### LINKED ISSUE #249: `get_magnetic_symmetry_dataset` causes segmentation fault for higher `mag_symprec`
## Describe the bug

The following magnetic structure with `mag_symprec=1e-1` causes a segmentation fault (CC: @nomoto21 ).

For Python API:
```python
lattice = np.array([
    [0.00000000, 0.00000000, -4.05000000],
    [-5.00000000, 0.00000000, 0.00000000],
    [-2.50000000, 4.33012702, 0.00000000],
])
positions = np.array([
    [0.50000000, 0.33333333, 0.33333333],
    [0.50000000, 0.66666667, 0.66666667],
    [0.00000000, 0.00000000, 0.00000000],
    [0.00000000, 0.00000000, 0.50000000],
    [0.00000000, 0.50000000, 0.50000000],
    [0.00000000, 0.50000000, 0.00000000],
])
numbers = np.array([1, 1, 1, 2, 2, 2])
magmoms = np.array([
    [-0.00200000, 0.00200000, 1.90000000],
    [0.00200000, 0.00000000, 1.91100000],
    [-0.00100000, 0.00200000, -2.23300000],
    [-0.00000000, -0.00000000, -0.06000000],
    [0.00000000, 0.00000000, -0.03200000],
    [0.00000000, -0.00000000, -0.02900000],
])
```

For C API:
```c
double lattice[3][3] = {
    { 0.00000000, -5.00000000, -2.50000000 },
    { 0.00000000, 0.00000000, 4.33012702 },
    { -4.05000000, 0.00000000, 0.00000000 },
};
double positions[][3] = {
    { 0.50000000, 0.33333333, 0.33333333 },
    { 0.50000000, 0.66666667, 0.66666667 },
    { 0.00000000, 0.00000000, 0.00000000 },
    { 0.00000000, 0.00000000, 0.50000000 },
    { 0.00000000, 0.50000000, 0.50000000 },
    { 0.00000000, 0.50000000, 0.00000000 },
};
int types[] = {1, 1, 1, 2, 2, 2};
double spins[] = {
    -0.00200000, 0.00200000, 1.90000000,
    0.00200000, 0.00000000, 1.91100000,
    -0.00100000, 0.00200000, -2.23300000,
    -0.00000000, -0.00000000, -0.06000000,
    0.00000000, 0.00000000, -0.03200000,
    0.00000000, -0.00000000, -0.02900000,
};
int num_atom = 6;
```

## Expected behavior

Of course, such a segmentation fault should not happen.

## Environment

- Python version: 3.10.9
- Spglib's version: 2.0.2

### PR DESCRIPTION
**Pull request by lan496**
Fixes: https://github.com/spglib/spglib/issues/249

In the example, the orders of FSG and XSG are not consistent due to high `mag_symprec`.
The PR validates the consistency (by checking a returned construct type from 1 to 4).

### CODE REVIEW

**Comment by lan496** [comment]
@LecrisUT The test with Address sanitizer for LLVM failed, but one for GCC succeeded. I have no idea why this difference happened. Do you have any idea?

**Comment by LecrisUT** [comment]
Ok, I have confirmed that only `llvm-ci` seems to fail. But note: we do not run sanitizers on intel. Maybe we should fix that.

I don't know much about address sanitizer since I default to C++ most of the times, but I suspect it is about pointers being mismanaged or different default sizes being used. I can try to run it locally with the debugger and check the execution if there is anything fishy.

Oh, the `goto` are just asking for trouble. Or at least in C++ those are banned.

**Comment by LecrisUT** [comment]
Here's a traceback that I got:
https://github.com/lan496/spglib/blob/93e22d723b2fec82e3f82be0985bba945a3f4b52/src/spglib.c#L343
https://github.com/lan496/spglib/blob/93e22d723b2fec82e3f82be0985bba945a3f4b52/test/test_magnetic_symmetry.cpp#L424

As far as I can see with my debugger, after `spgms_get_magnetic_dataset()` when it trigerred `get_reference_space_group()` with `type == 0`, `dataset` has no pointers initialized values.

The main issue I see is here:
```c
    SpglibMagneticDataset *dataset;
    spgms_get_magnetic_dataset(lattice, positions, types, tensors, 1, num_atoms,
                               1, symprec, -1, mag_symprec);

    free(rotations);
    free(translations);
    free(spin_flips);
    free(time_reversals);
    if (dataset != NULL) spg_free_magnetic_dataset(dataset);
```

`dataset` is never used anywhere, not in `spgms_get_mangetic_dataset`. One reason you didn't get an error is that llvm did not initialize it to `NULL`

File: test/test_magnetic_symmetry.cpp [hunk 1]
```diff
@@ -364,6 +364,66 @@ TEST(test_magnetic_symmetry, test_spg_get_symmetry_with_tensors_rough_symprec) {
...
+    size = spgms_get_symmetry_with_site_tensors(
+        rotations, translations, equivalent_atoms, primitive_lattice,
+        spin_flips, max_size, lattice, positions, types, tensors,
+        1 /* tensor_rank */, num_atoms, 1 /* with_time_reversal */,
+        1 /* is_axial */, symprec, -1 /* angle_tolerance */, mag_symprec);
+    ASSERT_TRUE(size > 0);
+
+    SpglibMagneticDataset *dataset;
+    spgms_get_magnetic_dataset(lattice, positions, types, tensors, 1, num_atoms,
+                               1, symprec, -1, mag_symprec);
```
Comment (LecrisUT) [inline test/test_magnetic_symmetry.cpp]:
```suggestion
    dataset = spgms_get_magnetic_dataset(lattice, positions, types, tensors, 1, num_atoms,
                               1, symprec, -1, mag_symprec);
```
Here we are

**Review by LecrisUT — CHANGES_REQUESTED** [review]

File: src/magnetic_spacegroup.c [hunk 2]
```diff
@@ -438,6 +438,9 @@ static int get_reference_space_group(Spacegroup **ref_sg,
     /* Determine type of MSG and generator of factor group of MSG over XSG */
     type = get_magnetic_space_group_type(&representatives, magnetic_symmetry,
                                          sym_fsg->size, sym_xsg->size);
+    if (type == 0) {
+        goto err;
+    }
     debug_print("type=%d\n", type);
```
Comment (LecrisUT) [inline src/magnetic_spacegroup.c]: Switch the order here
```suggestion
    debug_print("type=%d\n", type);
    if (type == 0) {
        goto err;
    }
```

File: test/test_magnetic_symmetry.cpp [hunk 3]
```diff
@@ -364,6 +364,67 @@ TEST(test_magnetic_symmetry, test_spg_get_symmetry_with_tensors_rough_symprec) {
...
+        rotations, translations, equivalent_atoms, primitive_lattice,
+        spin_flips, max_size, lattice, positions, types, tensors,
+        1 /* tensor_rank */, num_atoms, 1 /* with_time_reversal */,
+        1 /* is_axial */, symprec, -1 /* angle_tolerance */, mag_symprec);
+    ASSERT_TRUE(size > 0);
+
+    SpglibMagneticDataset *dataset;
+    dataset =
+        spgms_get_magnetic_dataset(lattice, positions, types, tensors, 1,
+                                   num_atoms, 1, symprec, -1, mag_symprec);
```
Comment (LecrisUT) [inline test/test_magnetic_symmetry.cpp:421]: Shouldn't you assert that `dataset == NULL`? (After you initialize to `NULL`). My understanding is that `spgms_get_magnetric_dataset` should always fail here right?

**Review by LecrisUT — CHANGES_REQUESTED** [review]
When possible, can you add some quick comments in the code, e.g. why `ASSERT_TRUE(size>0)`, or why/where it should fail?

File: test/test_magnetic_symmetry.cpp (hunk 3 above)
Comment (lan496) [reply test/test_magnetic_symmetry.cpp:421]: Yes, I am adding a short comment.

Comment (LecrisUT) [reply test/test_magnetic_symmetry.cpp:421]: I mean not just comment, isn't this section the main part that you are testing here, and isn't it expected to always fail and return null? It seems weird that when I ran the test, it returned not-null when there is in `get_magnetic_dataset()`:
```c
    if (spglib_error_code == SPGLIB_SUCCESS) {
        return dataset;
    } else {
        spg_free_magnetic_dataset(dataset);
        return NULL;
    }
```
Something is fishy here

Comment (LecrisUT) [reply test/test_magnetic_symmetry.cpp:421]: Nvm, my last comment. :+1: to assert the null

**Review by LecrisUT — APPROVED** [review]
LGTM now w.r.t. C coding, but I'll let you guys confirm the technical details of this

**Comment by lan496** [comment]
@LecrisUT Many thanks! I'll merge this PR after atztogo checks.

**Review by atztogo — APPROVED** [review]

**Comment by atztogo** [comment]
Thanks @lan496 and @LecrisUT!
